### ISSUE TITLE
need text for letter to reviewers

### ISSUE THREAD

**Issue by timm** [researchart/fse16#1]
olga,
what special instructions for reviews?

1) Need your github ids
2) Note that this is an open reviewing process. so be polite and constructive  
3) what else?

mail to:

David Lo    davidlo@smu.edu.sg, Arie Gurfinkel arie@cmu.edu, Latifa Guerrouj     guerroujl@gmail.com, Mark Van Den Brand m.g.j.v.d.brand@tue.nl, Barbara Russo  barbara.russo@unibz.it, Christoph Treude  ctreude@gmail.com, Felienne Hermans   felienne@gmail.com, Collin McMillan   cmc@nd.edu, Hongyu Zhang hongyujohn@gmail.com, Emily Hill   emhill@drew.edu, Yasutaka Kamei kamei@ait.kyushu-u.ac.jp

**Comment by obaysal** [comment]
We would need to describe the review process: adding labels (e.g., adding review1 & Diamond) to the comment and a hyperlink of the comment (aka review) to the master's sheet once the review is submitted, keeping issues open, submitting review according to the scorecard (Insightful, Useful, Usable).

**Comment by timm** [comment]
The "master" sheet contains links to:
- the pdf of the document to be reviewed,
- the issue where all reviews will be written.

Your will used the master sheet for navigation and the GitHub issue system to make the reviews.

**IMPORTANT: never open or close any issue.** If you really need a new issue (for some reason), ask the chairs.

### Step 1: COIs

Before doing the reviews, fill your name (where appropriate) in the "Conflicts" sheet for any COIs in tiny.cc/fse16art.
- please use your GitHub ID.

### Step 2: Check review assignments

After receiving email from chairs, go to "papers per reviewer" in tiny.cc/fse16art and check your assignments. Please email the chairs with any concerns. 

### Step 3: Do the Reviews
- Read assigned artifact papers. Each submission contains the following two pages:
  - _First_ page: authors' description of the artifact along the dimensions of the scorecard (i.e., Insightful, Useful, Usable).
  - _Second_ page: authors' description of how one can use the artifact (any difficulties one might encounter in using the artifact, or its maturity relative to the content of the paper). This page will be used in the proceedings if the artifact is accepted. The description of the artifact for the proceedings must not exceed 1 page (including all text, references, and figures).
- Do each review in the issue page assigned to this paper (see the "master" sheet of tiny.cc/fse16art , column F). Each review would essentially be added to the issue as a comment. 
- We strongly recommend that you do **NOT** read other reviews on the artifact **BEFORE** writing your own and posting it to the issue page.

### Step 4: Score the Artifact

When reviews are done, assign a label in the issue page as:
- **? maybe diamond:**  Award winning: most insightful, useful, and usable artifacts. Diamond artifacts will be given awards at a public session at FSE 2016, mentioned as part of the social media campaign for FSE 2016, and cataloged in an online repository.
- **? maybe platinum:** Very good: insightful, useful, and usable artifacts. Platinum artifacts will be mentioned as part of the social media campaign for FSE 2016 and cataloged in an online repository.
- **? maybe gold:** Potentially insightful, useful, or usable artifacts. Gold artifacts will be cataloged in an online repository.  
- **? maybe other:** Such artifacts are not to be included in the proceedings.

**Comment by obaysal** [comment]
@timm I have added the info about submissions and made minor edits.

**Comment by timm** [comment]
@tzimmermsr 

comments? on the above? or on the changes in http://tiny.cc/fse16art

**Comment by tzimmermsr** [comment]
How does Step 4 work? Who does the assignment: you as chairs? Or each reviewer?

Note that a label can be only assigned once to an issue.

**Comment by tzimmermsr** [comment]
In "papers per reviewer", does each reviewer get to do three reviews?

It might make sense to do one row per submission per reviewers (sorted by reviewer). It's easier to read tables vertically than horizontally and it allows you to scale. For the assignment you could also do it in GitHub (assign issue to reviewer)

**Comment by tzimmermsr** [comment]
"We strongly recommend that you do NOT read other reviews on the artifact BEFORE writing your own and posting it to the issue page."

Maybe you can add a direct link to the artifact in the spreadsheet?

**Comment by obaysal** [comment]
@tzimmermsr Step 4 is done by each reviewer. Labels can be added to the existing ones (not just replaced) and this makes it possible to have 3 different scoring labels from reviewers. If reviewers agree with the current label, no change is needed. Co-chairs will make final decisions.

**Comment by obaysal** [comment]
"papers per reviewers": I think it would be easier for reviewers to work with one row showing all their paper assignments. We don't know what would be the review load (x) per reviewer. Right now x=3 in this sheet. 

But @tzimmermsr suggestion would also work if the number of submissions is low.

**Comment by obaysal** [comment]
While "master" sheet contains direct link to the artifact submission (File Name), it's a good idea to add a link to the artifact for "papers per reviewers" tab too.
