### ISSUE TITLE
check labels with olga

### ISSUE THREAD

**Issue by timm** [researchart/fse16#2]
![image](https://cloud.githubusercontent.com/assets/29195/15723327/e8cc0e68-280f-11e6-9369-013a7f662e48.png)

**Comment by obaysal** [comment]
I think we should add another label/milestone such as "Decision Made" to indicate that the final decision on the artifact is done. If reviewers disagree, the artifact might have 2-3 different labels (e.g., Diamond, Platinum, Gold). We as co-chairs should make the final call in such cases once the discussion is over. What do you think @timm ?
