### ISSUE TITLE
for olga: next steps

### ISSUE THREAD

**Issue by timm** [researchart/fse16#26]
- [ ] olga: please check http://tiny.cc/fse16art {master}. note that i did not have FS paper ids so i added our own
- [ ] olga confirm: re  http://tiny.cc/fse16art {registrations}. my next step is to email reviewers and say (1) please register yourself at {registrations} and (2) mark your COIs on {conflicts, column E} and,(3), optionally, if you want to, volunteer to review a paper by adding your name to columns F,G,H

**Comment by obaysal** [comment]
@timm I can pull paper IDs from the file Jane sent to us. 

@timm next step sounds good to me.

**Comment by timm** [comment]
> @timm I can pull paper IDs from the file Jane sent to us.

please do

> @timm next step sounds good to me.

mail sent,

```
Dear all,

Thank you for volunteering to review artifacts for FSE'16.   

This email lists the first steps in that process. 
Please complete the following by Friday this week.

First, please register your github id in column A 
of the "registrations" tab of http://tiny.cc/fse16art 

Second, please record your conflict of interests in 
column E of the "conflicts" tab of http://tiny.cc/fse16art 

Third, (optional) please feel  volunteer to review some 
artifacts in column F,G,H of the "conflicts" tab of http://tiny.cc/fse16art.  

Fourth (and this is an important step: WAIT. Do not 
review artifacts, yet (since first we may have to juggle 
assignments to ensure coverage and address COI issues)

Best regards,

Olga + Timm
```

**Comment by timm** [comment]
for fse. tomorrow i'll work the icsme16 master control sheet 

unless you get there first of course :relaxed:

**Comment by obaysal** [comment]
FSE paper IDs are added to the master control sheet.
