### ISSUE TITLE
ask tom: how to using github for reviewing

### ISSUE THREAD

**Issue by timm** [researchart/fse16#3]
tom
please check tiny.cc/fse16art 

this is our proposed master sheet for reviewing fss artifacts

any suggestions? (i ask due to your experience with the superdog book)

t

**Comment by tzimmermsr** [comment]
The GitHub master sheet looks good. I recommend
- Ask for FSE paper number
- Add a column with the link to the Issue to the report. I personally just copy paste the URLs in the last  column at the end of the spreadsheet; you can then create nicer links in earlier column by referencing the other column, e.g. =HYPERLINK(H2,ʺolgaʺ)

The review assignment is a good overview for you as a _chair_. Not sure if you need links for each reviewer. Maybe just add a completed column for each reviewer, where they can check off.

For the _reviewers_, I would assign them to the GitHub issues that they are supposed to review (you can assign up to 10 people). That way they get notifications and they can easily find all the artifacts that they are assigned to.

You want the reviews in a single issue. Don't have reviewers create a separate issue for their reviews.

Tracking the progress with the labels didn't work very well for the super dog book. Sometime people forgot. I would simply track the progress with the Google sheet. 

Ask reviewers not to close issues.

Hope that helps.

**Comment by tzimmermsr** [comment]
Haven't tried it yet but Milestones might be better to track progress instead of labels.

One issue with labels is that you have to remove the old label, when you set a new label

**Comment by tzimmermsr** [comment]
I think when reviewers are done with a review, they can un-assign them. They should still get email notification as participant.

**Comment by timm** [comment]
thanks for your attention to these details

If we can develop good open review procedures, sans easychair et al, that would change... much.

**Comment by obaysal** [comment]
Thank you @tzimmermsr for your detailed recommendations! These are very useful!
