### ISSUE TITLE
email template

### ISSUE THREAD

**Issue by timm** [researchart/fse16#8]
Thanks for your submission. 

> Our reply to you will point to a GitHub repository 

https://github.com/researchart/fse16

> and a directory for submissions. 

https://github.com/researchart/fse16/tree/master/submissions/XXX

> Drag and drop your PDF onto that directory.
> 
> Create an issue in that repository whose title is the XXX_YYY. Do not add any text to the comment.

Olga & Tim

**Comment by obaysal** [comment]
Dear XXX,

Thank you for submission! Please note the following next steps (taken from our CFP). If you have any technical issues with the following (e.g., you are not familiar with using GitHub) then please contact us and we will do the following for you.

1) FSE-16 Artifacts GitHub repository:

https://github.com/researchart/fse16/

2) Your directory for submissions:

https://github.com/researchart/fse16/tree/master/submissions/XXX

3) Drag and drop your PDF onto that directory.

4) Create an issue in that repository whose title is the XXX_YYY. Do not add any text to the comment.

Regards,

Olga & Tim
