### ISSUE TITLE
register users

### ISSUE THREAD

**Issue by timm** [researchart/fse16#9]
- [x] weiwei16 
- [x] danilofes 
- [x] mreif
- [x] stahlbauer 
- [x] monikadhok 
- [x] sch8906
- [x] mikefhsu
- [x] adarshyoga
- [x] andrew659
- [x] floatfeather  
- [x] hjjandy  
- [x] mdangl  
- [x] nirhasabnis  
- [x] obaysal  
- [x] rockysui  
- [x] qhanam  
- [x] timm
- [x] zhaoguixu

**Comment by timm** [comment]
in order to allow them to push pull files, i had to give the repo write permission

is this dangerous? or is it in the spirit of open source?

![image](https://cloud.githubusercontent.com/assets/29195/16417772/2dd6fd6e-3d15-11e6-8129-d9024e439270.png)

**Comment by obaysal** [comment]
giving write permissions should be fine! i don't see a problem with this, we are using git we can always undo any undesired changes.

**Comment by timm** [comment]
i need to get with grad students to work out the github api.  we could extend the "register" script to auto add them as collaborators. that script would need to access  a magic authorization key which, if we kept it out of the repo and on our local hard drives,  then the script could still be in the repo while keeping the key secret

more generally, my open question to you is?
- what are the N tasks that we can automate to turn standard github into a viable open review system?

**Comment by timm** [comment]
oh- and here's the notes on "owners" (you and me) vs collaborators (everyone else). looks like we have to make our pc people "collaborators". do you concur?

![image](https://cloud.githubusercontent.com/assets/29195/16420251/a1c35368-3d1e-11e6-917a-0646cef2e4b3.png)

**Comment by obaysal** [comment]
I think reviewers do _not_ have to be collaborators since they will only comment on issues and add labels.
